### ISSUE TITLE
warning message with PCAtools

### ISSUE THREAD

**Issue by gexijin** [espors/idepGolem#107]
**what**
Many warning messages are shown when the PCAtools subtab is clicked.
"Warning in check_numbers(x, k = k, nu = nu, nv = nv) :
  more singular values/vectors requested than available"
The code seems to run anyway.

**To reproduce**
Load the demo data and then go to PCAtools subtab in PCA tab. 
Dozens of warning show up in the R console.

**Comment by espors** [comment]
@bderenge This seems to be resolved. Can we close this issue.
