### ISSUE TITLE
For package use, will need to add "export" to .rd of functions 

### ISSUE THREAD

**Issue by espors** [espors/idepGolem#141]
**What** 
Functions within idepGolem app will not be available for use when run as a package by others unless `@export` is added to function description/.rd file.

**Comment by bderenge** [comment]
Can this be done with roxygen by adding #'@export above each function? Currently the only function with @export is run_app, which I think is by design, its a feature of Golem.

**Comment by espors** [comment]
Yep - we add @export to the the roxygen comment!

**Comment by espors** [comment]
Without adding this, users will not be able to access the functions for inline programming
