### ISSUE TITLE
Gene ID Label Mismatch

### ISSUE THREAD

**Issue by bderenge** [espors/idepGolem#153]
Users can select how gene names appear on clustering tab and PCAtools plots. The options are User_id, Ensembl_id, and symbol. On the Load Data page, users can check "Do not convert to Ensembl."
What is the intended use of "Do not convert to Ensembl"? Is it meant to be used if the data already has Ensembl ids? Or, does the user simply want to keep whatever label are initially in the data?

The demo data has Ensembl ids, and "do not convert to ensembl" is unchecked. When selecting row ids on clustering and on PCAtools plots, userId appears to be switched with Ensembl_id, and symbol looks correct. Similar errors occur if the data is uploaded with symbols as rownames.

To Reproduce
Run app and load demo data. Go to clustering and highlight a small section of the heatmap. Check if row id is selected matches the id appearing on the small heatmap. Then change  row id and see the updated id appears on the map. Userid should be incorrectly showing Ensembl id and Ensembl id shows row numbers.

![rowid_mismatch](https://user-images.githubusercontent.com/58050643/173881186-74801392-2e24-4fb8-92bd-c3ba67c587e9.PNG)
![gene_id_mismatch2](https://user-images.githubusercontent.com/58050643/173881202-0d77d5c3-810a-4493-87ba-dbf44fbe28f6.PNG)

**Comment by bderenge** [comment]
Related to this, rowname_id_swap() might be adding a leading space before each gene name. This comes up when calling the individual gene plot on the preprocess tab and the preprocess vignette.
![image](https://user-images.githubusercontent.com/58050643/175353129-3058c4c3-d2ba-4722-8143-5dc8808cc171.png)

individual_plots(
  individual_data = ind_plot_data,
  sample_info = load_data$sample_info,
  selected_gene = " Ankrd13b",
  gene_plot_box = TRUE,
  use_sd = FALSE,
  lab_rotate = 90
)
Notice that the space before " Ankrd13b" in the selected_gene parameter is necessary for the plot to generate.

**Comment by gexijin** [comment]
This is fixed.

**Comment by gexijin** [comment]
Reopen because of the second issues related to the space characters.
