### ISSUE TITLE
Error on Genome tab "Could not find function sampleNames"

### ISSUE THREAD

**Issue by gexijin** [espors/idepGolem#175]
**To reproduce**
Load the demo data. In DEG1 tab, define comparisons. 
Click Genome tab, then PREDA.

**Comment by espors** [comment]
@gexijin Try updating the package? I think I had recently updated mine and now this tab is working for me.

**Comment by espors** [comment]
![image](https://user-images.githubusercontent.com/71563929/186996174-644b058a-ee18-48d5-a61d-04ee7f3e6d74.png)

**Comment by gexijin** [comment]
I fixed this issue but forgot to close this issue. The problem is that sampleNames is a function used in PREDA. The PREDA library has to be loaded using library(PREDA). Gavin won't like this but I can't find a better way.
