### ISSUE TITLE
Auto reset the app when a second dataset is uploaded in a session

### ISSUE THREAD

**Issue by gexijin** [espors/idepGolem#243]
**Describe the feature**
When users uploaded one dataset, do some analysis and then upload a new dataset. If they do not click reset,
 currently we have a lot of issues. Maybe it is possible to reset automatically if users upload a new expression data?

**To Reproduce**
1. Upload one demo data, click on Pre-Process
2. Upload another demo data,

**Expected behavior**
The app should reset if a new dataset is uploaded.

**Comment by gexijin** [comment]
Great idea. Never thought of that.

**Comment by espors** [comment]
Or add error and force them to reset the app before they can upload new dataset
