### ISSUE TITLE
Load demo data button [Load Data] 

### ISSUE THREAD

**Issue by espors** [espors/idepGolem#285]
**Describe the bug**
If you press the "Load demo data" button before the choices populate for the drop-down, the application will crash. 

**To Reproduce**
1. Reset the application 
2. Click on load demo data quickly (i.e. before the dropdown populations)
3. Note crashed application 

**Expected behavior**
The button is not available until the dropdown populations.

**Comment by gexijin** [comment]
Yes, I am aware of this. No idea how to solve this. Hopefully they will be distracted for a few seconds.

**Comment by bderenge** [comment]
Maybe if we include req(input$selected_species) in the output$demo_button section then the button won't do anything until input$selected species is no longer null. It's a simple fix but it has worked in similar situations
