### ISSUE TITLE
PCA tab: Add 3-D plots

### ISSUE THREAD

**Issue by gexijin** [espors/idepGolem#306]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
There are so many principal components, it might be useful for some users to generate an interactive 3D scatter plot.

**Describe the solution you'd like**
An interactive 3D scatter plot using the first 3 components.

**Comment by EricTulowetzke** [comment]
This can be done with R plotty which we can look at if plotly is a good package for us to add

https://plotly.com/r/pca-visualization/

**Comment by EricTulowetzke** [comment]
I will take over this and do this before #303
