### ISSUE TITLE
Error with tippy on load data

### ISSUE THREAD

**Issue by gexijin** [espors/idepGolem#332]
**Describe the bug**
Error message with commit [92f3211](https://github.com/espors/idepGolem/commit/92f3211acd10a094462d9245896132f3f383e939).

**To Reproduce**
1. Define a new branch from this commit.
2. Click on Load demo
3. Error: 
 Error in $: $ operator is invalid for atomic vectors
  tippy::with_tippy
  renderUI [C:/work/idepGolem/R/mod_01_load_data.R#300]

**Additional context**
I had to delete this chuck for it to work.
            tippy::with_tippy(
              ns("reset_data"),
              "Reset the entire application"
            )

**Comment by EricTulowetzke** [comment]
@gexijin My local master on commit 74dd6d34 works fine so for now I recommend forking from there and then merge your branch to that branch then overwrite commit [92f3211](https://github.com/espors/idepGolem/commit/92f3211acd10a094462d9245896132f3f383e939).

**Comment by gexijin** [comment]
I deleted the reset button for simplicity. we already have one there.
