### ISSUE TITLE
Show top genes on volcano plots

### ISSUE THREAD

**Issue by JianYes** [espors/idepGolem#347]
**Is your feature request related to a problem? What value do you see this adding? Please describe.**
On the volcanoplot, could we also have an option of showing let say to 20 most differentially expressed genes?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gexijin** [comment]
This uses the ggrepel package to label genes: 
![image](https://user-images.githubusercontent.com/18232433/193417268-a6e10d8a-c47e-4462-af7b-7c6e8fed3f32.png)
