### ISSUE TITLE
NGA: Add Submit Button to All Tabs 

### ISSUE THREAD

**Issue by espors** [espors/idepGolem#37]
**What:** Add a submit button on all tabs so that given calculations are not completed until after user hits "submit" 

**Why:** Improve user experience. 
Currently, on most of the tabs, if any of the input values change, the app will rerun all of the calculations -- this can be slow and there is not a way to stop it in the middle if you made a mistake. 
Some users may not know which values or choices they want right away or may select the wrong values. 
By adding a submit button, the calculations won't be made until the users are satisfied with their input. 

**Proposed Steps:** 

**Approved:**

**Comment by EricTulowetzke** [comment]
I agree with this but get @gexijin to agree to it. We have some submit buttons ready. do we want to add more? do we want to close this issues?

**Comment by gexijin** [comment]
I do not like submit buttons. Unless it is too much computing time hinders user experience.  Let's close this for now.
