### ISSUE TITLE
PCA plot legends, interactive as an option?

### ISSUE THREAD

**Issue by gexijin** [espors/idepGolem#380]
**Describe the bug**
When there are two factors, the main PCA plot legends are wrong. This is probably caused by switching to plotly.
A possible solution is to enable both interactive and non-interactive plots.

**To Reproduce**
1. Load the 2x2 design demo data
2. Click on PCA tab, select p53 for the Shape, and treatment as color. The legends are not as intuitive
![image](https://user-images.githubusercontent.com/18232433/194597462-1c01d7a0-e3db-410a-92a6-c8add4fd2b19.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/18232433/194597316-886011ff-c56e-4b0d-8172-b522a4e797d4.png)

**Screenshots**

**Additional context**

**Comment by bderenge** [comment]
In the screenshot, the legends look correct. The points are the same on both plots.
Also, when the interactive plot is downloaded, the non-interactative version of the plot is pass to the ottoplots module, to the legend appear as it does in the second screenshot in the downloaded .png file
