### ISSUE TITLE
Missing gene plot [Pre-process] 

### ISSUE THREAD

**Issue by espors** [espors/idepGolem#392]
**Describe the bug**
The gene plot in the Pre-Process tab is missing after applying the new bslib theme.

**To Reproduce**
1. Load demo data 
2. Go to Pre-Processing tab -> Gene plot 
3. Note missing plot 

**Expected behavior**
Plot generates

**Comment by espors** [comment]
Fix in conjunction with #379

**Comment by gexijin** [comment]
I think it is fixed. 
https://github.com/espors/idepGolem/commit/c06d019c6e8fe9f024f376a0fac7485d09c79c4d
