### ISSUE TITLE
NGA: Create downloadable "Workflow" document 

### ISSUE THREAD

**Issue by espors** [espors/idepGolem#43]
**Concept**
On the last tab, have a "Download Workflow" option which downloads a file containing inputs from the app. I.e., type of gene count cutoffs, data transformation, p-value cutoff values, etc..

**Pros** 
-You cannot save the "state" of an app, so if the app crashes after they have saved the file, they have a record of the selections they made. 
-It would encourage reproducibility in research. 

**Cons**
-Would this add to confusion for the user. For example, you can perform a VST transformation on the data, but that is only used for data visualization, not in the DEGs, but would this be clear in the file? 
-This could be unneeded. Users *should* be tracking their own input.

**Comment by bderenge** [comment]
I think we can put a "download report" button on each page. This would have all parameters selected in the tab's ui and the rmarkdown file it generates would have the code and the images from that tab.
https://shiny.rstudio.com/articles/generating-reports.html
