### ISSUE TITLE
[all tabs with images] Image Download Options 

### ISSUE THREAD

**Issue by bderenge** [espors/idepGolem#80]
https://stackoverflow.com/questions/70229801/high-resolution-adjustable-figures-in-shiny

We will need to add options to download high resolution images to any tab with a plot.

**Comment by espors** [comment]
@bderenge Not sure if you have started anything with this, but I had played around with a bit of the code already

**Comment by espors** [comment]
- Turn graphs in into reactive element, use that to create graph output and download function 
- Look into creating a ui module for reusing code across all graphs

**Comment by espors** [comment]
-[] #82

**Comment by espors** [comment]
Created ottoPlots package with module functionality. Please use that package going forward.

**Comment by EricTulowetzke** [comment]
@espors and @gexijin can we we close this issue now?

**Comment by espors** [comment]
Module has been added to plots.
